# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secknowledgemodel',
            options={'verbose_name': '\u9632\u707d\u4e88\u5099\u77e5\u8b58', 'verbose_name_plural': '\u9632\u707d\u4e88\u5099\u77e5\u8b58'},
        ),
    ]
