# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='\u5e74\u5ea6')),
            ],
        ),
    ]
