# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u524d')),
                ('email', models.EmailField(max_length=70, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('title', models.CharField(help_text='\u8981\u4ef6\u540d\u3092\u8a18\u5165\u3057\u3066\u304f\u3060\u3055\u3044', max_length=200, verbose_name='\u4ef6\u540d')),
                ('body', models.TextField(verbose_name='\u5185\u5bb9')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='\u6295\u7a3f\u65e5')),
                ('finished', models.BooleanField(default=False, verbose_name='\u51e6\u7406\u6e08')),
            ],
        ),
    ]
