# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': '\u304a\u554f\u3044\u5408\u308f\u305b', 'verbose_name_plural': '\u304a\u554f\u3044\u5408\u308f\u305b'},
        ),
    ]
