# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoEntryModel',
        ),
    ]
