# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoentrymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoentrymodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
