# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 13:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import publish.models.board


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('modified', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u516c\u958b\u958b\u59cb')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u4ee5\u964d\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u6709\u52b9\u671f\u9650')),
                ('title', models.CharField(max_length=200, verbose_name='\u984c\u540d')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u5165\u529b\u30dc\u30c3\u30af\u30b9\u306e\u6a2a\u5e45\u304c\u6539\u884c\u306e\u5927\u4f53\u306e\u76ee\u5b89\u3067\u3059', null=True, verbose_name='\u672c\u6587')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u8a18\u4e8b\u306e\u8aac\u660e')),
            ],
            options={
                'verbose_name': '\u6d3b\u52d5\u5831\u544a',
                'verbose_name_plural': '\u6d3b\u52d5\u5831\u544a',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('modified', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u516c\u958b\u958b\u59cb')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u4ee5\u964d\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u6709\u52b9\u671f\u9650')),
                ('title', models.CharField(max_length=255, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('file', models.FileField(upload_to=b'boards/', validators=[publish.models.board.validate_file_pdf], verbose_name=b'PDF')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=b'boards/', verbose_name='\u30b5\u30e0\u30cd\u30a4\u30eb')),
            ],
            options={
                'verbose_name': '\u56de\u89a7\u7269',
                'verbose_name_plural': '\u56de\u89a7\u7269',
            },
        ),
        migrations.CreateModel(
            name='NewsCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='8\u6587\u5b57\u4ee5\u5185', max_length=8, unique=True, verbose_name='\u30ab\u30c6\u30b4\u30ea\u30fc\u540d')),
                ('fgcolor', colorfield.fields.ColorField(default=b'#ffffff', max_length=10, verbose_name='\u6587\u5b57\u8272')),
                ('bgcolor', colorfield.fields.ColorField(default=b'#ff0000', max_length=10, verbose_name='\u80cc\u666f\u8272')),
                ('sortid', models.IntegerField(db_index=True, default=0, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name=' ')),
            ],
            options={
                'ordering': ['sortid'],
                'verbose_name': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc',
                'verbose_name_plural': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc',
            },
        ),
        migrations.CreateModel(
            name='NewsPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('modified', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u516c\u958b\u958b\u59cb')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u4ee5\u964d\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u6709\u52b9\u671f\u9650')),
                ('title', models.CharField(max_length=200, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('url', models.URLField(verbose_name=b'URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.NewsCategoryModel')),
            ],
            options={
                'verbose_name': '\u304a\u77e5\u3089\u305b',
                'verbose_name_plural': '\u304a\u77e5\u3089\u305b',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u30bf\u30b0')),
            ],
            options={
                'verbose_name': '\u6d3b\u52d5\u30bf\u30b0',
                'verbose_name_plural': '\u6d3b\u52d5\u30bf\u30b0',
            },
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.NewsPostModel'),
        ),
        migrations.AddField(
            model_name='activitypostmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.NewsPostModel'),
        ),
        migrations.AddField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text=b'\xe5\xbd\x93\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xbe\xe3\x82\x8b\xe9\xa0\x85\xe7\x9b\xae\xe3\x82\x92\xe3\x81\x99\xe3\x81\xb9\xe3\x81\xa6\xe9\x81\xb8\xe3\x82\x93\xe3\x81\xa7\xe3\x81\x8f\xe3\x81\xa0\xe3\x81\x95\xe3\x81\x84<br>', related_name='tagging', to='publish.TagModel'),
        ),
    ]
