# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.NewsPostModel', verbose_name='\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc'),
        ),
        migrations.AlterField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text=b'\xe5\xbd\x93\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xbe\xe3\x82\x8b\xe9\xa0\x85\xe7\x9b\xae\xe3\x82\x92\xe3\x81\x99\xe3\x81\xb9\xe3\x81\xa6\xe9\x81\xb8\xe3\x82\x93\xe3\x81\xa7\xe3\x81\x8f\xe3\x81\xa0\xe3\x81\x95\xe3\x81\x84<br>', related_name='tagging', to='publish.TagModel', verbose_name='\u30bf\u30b0'),
        ),
        migrations.AlterField(
            model_name='newspostmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.NewsCategoryModel', verbose_name='\u30ab\u30c6\u30b4\u30ea\u30fc'),
        ),
    ]
