# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:01
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_newspostmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='\u30ab\u30c6\u30b4\u30ea\u30fc\u540d')),
                ('fgcolor', colorfield.fields.ColorField(default=b'#ffffff', max_length=10, verbose_name='\u6587\u5b57\u8272')),
                ('bgcolor', colorfield.fields.ColorField(default=b'#ff0000', max_length=10, verbose_name='\u80cc\u666f\u8272')),
            ],
            options={
                'verbose_name': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc',
                'verbose_name_plural': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc',
            },
        ),
    ]
