# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_newscategorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategorymodel',
            options={'ordering': ['sortid'], 'verbose_name': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc', 'verbose_name_plural': '\u304a\u77e5\u3089\u305b\u30ab\u30c6\u30b4\u30ea\u30fc'},
        ),
        migrations.AddField(
            model_name='newscategorymodel',
            name='sortid',
            field=models.IntegerField(db_index=True, default=0, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='newscategorymodel',
            name='name',
            field=models.CharField(help_text='8\u6587\u5b57\u4ee5\u5185', max_length=8, verbose_name='\u30ab\u30c6\u30b4\u30ea\u30fc\u540d'),
        ),
    ]
