# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20160302_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspostmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.NewsCategoryModel'),
        ),
    ]
