# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20160302_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u5165\u529b\u30dc\u30c3\u30af\u30b9\u306e\u6a2a\u5e45\u304c\u6539\u884c\u306e\u5927\u4f53\u306e\u76ee\u5b89\u3067\u3059', null=True, verbose_name='\u672c\u6587'),
        ),
    ]
