# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_auto_20160302_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u30bf\u30b0')),
            ],
        ),
        migrations.AddField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='publish.TagModel'),
        ),
    ]
