# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 02:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_auto_20160302_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypostmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.NewsPostModel'),
        ),
        migrations.AlterField(
            model_name='activitypostmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u5165\u529b\u30dc\u30c3\u30af\u30b9\u306e\u6a2a\u5e45\u304c\u6539\u884c\u306e\u5927\u4f53\u306e\u76ee\u5b89\u3067\u3059', null=True, verbose_name='\u672c\u6587'),
        ),
        migrations.AlterField(
            model_name='activitypostmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u72b6\u614b'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u72b6\u614b'),
        ),
        migrations.AlterField(
            model_name='newspostmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u72b6\u614b'),
        ),
    ]
