# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_auto_20160302_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publish.TagModel'),
        ),
    ]
