# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_auto_20160302_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypostmodel',
            name='news',
        ),
    ]
