# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_auto_20160302_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u30bf\u30b0'),
        ),
    ]
