# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0013_auto_20160302_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tagging', to='publish.TagModel'),
        ),
    ]
