# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0014_auto_20160302_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='\u5e74\u5ea6'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='\u5e74\u5ea6'),
        ),
        migrations.AlterField(
            model_name='newspostmodel',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='\u5e74\u5ea6'),
        ),
    ]
