# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0015_auto_20160302_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9'),
        ),
        migrations.AlterField(
            model_name='activitypostmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagging', to='publish.TagModel', verbose_name=b'\xe3\x82\xbf\xe3\x82\xb0\xef\xbc\x88\xe5\xbd\x93\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xbe\xe3\x82\x8b\xe9\xa0\x85\xe7\x9b\xae\xe3\x82\x92\xe3\x81\x99\xe3\x81\xb9\xe3\x81\xa6\xe9\x81\xb8\xe3\x82\x93\xe3\x81\xa7\xe3\x81\x8f\xe3\x81\xa0\xe3\x81\x95\xe3\x81\x84\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9'),
        ),
        migrations.AlterField(
            model_name='newspostmodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9'),
        ),
    ]
