# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publish.models.board


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0019_activitypostmodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypostmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.NewsPostModel'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(upload_to=b'boards/', validators=[publish.models.board.validate_file_pdf], verbose_name=b'PDF'),
        ),
    ]
