# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0020_auto_20160307_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategorymodel',
            name='name',
            field=models.CharField(help_text='8\u6587\u5b57\u4ee5\u5185', max_length=8, unique=True, verbose_name='\u30ab\u30c6\u30b4\u30ea\u30fc\u540d'),
        ),
    ]
