# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0021_auto_20160307_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': '\u6d3b\u52d5\u30bf\u30b0', 'verbose_name_plural': '\u6d3b\u52d5\u30bf\u30b0'},
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publish.NewsPostModel'),
        ),
    ]
