# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satoformat',
            name='file',
            field=models.FileField(blank=True, upload_to='formats', verbose_name='PDF'),
        ),
    ]
