# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0002_auto_20160206_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherformat',
            name='sortid',
            field=models.IntegerField(default=100, verbose_name='\u4e26\u3073\u756a\u53f7(\u8868\u793a\u6642\u306b\u5c0f\u3055\u3044\u9806\u306b\u4e26\u3073\u307e\u3059)'),
        ),
    ]
