# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0002_remove_satoformat_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satoformat',
            options={'ordering': ('position',), 'verbose_name': '\u91cc\u81ea\u6cbb\u4f1a\u95a2\u4fc2\u66f8\u5f0f', 'verbose_name_plural': '\u91cc\u81ea\u6cbb\u4f1a\u95a2\u4fc2\u66f8\u5f0f'},
        ),
        migrations.AddField(
            model_name='satoformat',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
