# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0003_auto_20160229_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satoformat',
            options={'ordering': ['sortid'], 'verbose_name': '\u91cc\u81ea\u6cbb\u4f1a\u95a2\u4fc2\u66f8\u5f0f', 'verbose_name_plural': '\u91cc\u81ea\u6cbb\u4f1a\u95a2\u4fc2\u66f8\u5f0f'},
        ),
        migrations.RemoveField(
            model_name='satoformat',
            name='position',
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='sortid',
            field=models.IntegerField(db_index=True, default=0, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name='\u4e26\u3073\u756a\u53f7'),
        ),
    ]
