# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0004_auto_20160206_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherformat',
            name='sortid',
            field=models.IntegerField(default=100, verbose_name='\u4e26\u3073\u756a\u53f7(\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059)'),
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='sortid',
            field=models.IntegerField(default=100, verbose_name='\u4e26\u3073\u756a\u53f7(\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059)'),
        ),
    ]
