# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0005_auto_20160229_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satoformat',
            options={'ordering': ['sortid'], 'verbose_name': '\u91cc\u81ea\u6cbb\u4f1a\u5411\u3051\u95a2\u4fc2\u66f8\u5f0f', 'verbose_name_plural': '\u91cc\u81ea\u6cbb\u4f1a\u5411\u3051\u95a2\u4fc2\u66f8\u5f0f'},
        ),
    ]
