# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0005_auto_20160206_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherformat',
            name='sortid',
            field=models.IntegerField(default=100, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name='\u4e26\u3073\u756a\u53f7(\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059)'),
        ),
        migrations.AlterField(
            model_name='otherformat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u66f8\u5f0f\u540d'),
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='sortid',
            field=models.IntegerField(default=100, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name='\u4e26\u3073\u756a\u53f7(\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059)'),
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u66f8\u5f0f\u540d'),
        ),
    ]
