# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 12:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0007_auto_20160207_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherformat',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u6982\u8981'),
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u6982\u8981'),
        ),
    ]
