# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0007_auto_20160302_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallBookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=200, verbose_name='\u56e3\u4f53\u540d')),
                ('address', models.CharField(max_length=200, verbose_name='\u4f4f\u6240')),
                ('name', models.CharField(max_length=200, verbose_name='\u6c0f\u540d')),
                ('phone', models.CharField(max_length=15, verbose_name='TEL')),
                ('email', models.EmailField(max_length=100, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('purpose', models.CharField(max_length=200, verbose_name='\u4f7f\u7528\u76ee\u7684(\u4f1a\u5408\u540d\u79f0)')),
                ('start_date', models.DateTimeField(verbose_name='\u5e0c\u671b\u958b\u59cb\u6642\u9593')),
                ('end_date', models.DateTimeField(verbose_name='\u7d42\u4e86\u4e88\u5b9a\u6642\u9593')),
                ('body', models.TextField(verbose_name='\u5099\u8003')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='\u6295\u7a3f\u65e5')),
                ('finished', models.BooleanField(verbose_name='\u51e6\u7406\u6e08\u307f')),
            ],
            options={
                'verbose_name': '\u91cc\u516c\u6c11\u9928\u4f7f\u7528\u7533\u8fbc',
                'verbose_name_plural': '\u91cc\u516c\u6c11\u9928\u4f7f\u7528\u7533\u8fbc',
            },
        ),
    ]
