# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0008_hallbookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallBookingModel',
        ),
    ]
