# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0009_auto_20160229_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherformat',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satoformat',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
