# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0010_auto_20160229_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherformat',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u8981'),
        ),
        migrations.AlterField(
            model_name='satoformat',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u8981'),
        ),
    ]
