# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20160203_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='category',
            field=models.IntegerField(choices=[(1, '\u91cd\u8981'), (2, '\u304a\u77e5\u3089\u305b'), (3, '\u9632\u72af'), (4, '\u3054\u5831\u544a'), (5, '\u884c\u4e8b'), (6, '\u52df\u96c6'), (7, '\u66f4\u65b0')], default=2, verbose_name='\u304a\u77e5\u3089\u305b\u306e\u7a2e\u985e'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='\u516c\u958b\u3059\u308b'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u30bf\u30a4\u30c8\u30eb'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
