# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_auto_20160203_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '\u304a\u77e5\u3089\u305b', 'verbose_name_plural': '\u304a\u77e5\u3089\u305b'},
        ),
    ]
