# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_auto_20160203_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 3, 17, 48, 27, 494129), verbose_name='\u4f5c\u6210\u65e5\u6642'),
        ),
    ]
