# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0006_auto_20160203_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 3, 17, 54, 20, 942272), verbose_name='\u516c\u958b\u65e5\u6642'),
        ),
        migrations.AlterField(
            model_name='information',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u4f5c\u6210\u65e5\u6642'),
        ),
    ]
