# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0007_auto_20160203_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 3, 17, 54, 31, 51763), verbose_name='\u516c\u958b\u65e5\u6642'),
        ),
    ]
