# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecKnowledgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('description', models.TextField(blank=True, verbose_name='\u8aac\u660e\u6587')),
                ('url', models.URLField(verbose_name='URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='knowledge/', verbose_name='\u30b5\u30e0\u30cd\u30a4\u30eb')),
                ('image_status', models.BooleanField(choices=[(True, '\u7e26'), (False, '\u6a2a')], default=True, verbose_name='\u753b\u50cf\u306e\u72b6\u614b')),
                ('sortid', models.IntegerField(default=100, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name='\u4e26\u3073\u756a\u53f7')),
                ('publish', models.BooleanField(default=True, verbose_name='\u516c\u958b\u3059\u308b')),
            ],
            options={
                'verbose_name': '\u9632\u707d\u4e88\u5099\u77e5\u8b58',
                'verbose_name_plural': '\u9632\u707d\u4e88\u5099\u77e5\u8b58',
            },
        ),
    ]
