# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20160218_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secknowledgemodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u8aac\u660e\u6587'),
        ),
    ]
