# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_secknowledgemodel_horizontal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyentrymodel',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u4f5c\u6210\u65e5'),
        ),
        migrations.AlterField(
            model_name='emergencyentrymodel',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u7de8\u96c6\u65e5'),
        ),
    ]
