# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20160318_2323'),
        ('security', '0003_auto_20160325_2125'),
    ]

    operations = [
    ]
