# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_emergencyentrymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyentrymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u8981'),
        ),
    ]
