# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_secknowledgemodel_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secknowledgemodel',
            options={'ordering': ['sortid'], 'verbose_name': '\u9632\u707d\u4e88\u5099\u77e5\u8b58', 'verbose_name_plural': '\u9632\u707d\u4e88\u5099\u77e5\u8b58'},
        ),
        migrations.RemoveField(
            model_name='secknowledgemodel',
            name='image_status',
        ),
        migrations.AlterField(
            model_name='secknowledgemodel',
            name='sortid',
            field=models.IntegerField(db_index=True, default=0, help_text='\u30b5\u30a4\u30c8\u3067\u6607\u9806\u306b\u4e26\u3073\u307e\u3059', verbose_name=' '),
        ),
    ]
