# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20160229_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyentrymodel',
            name='status',
            field=models.IntegerField(choices=[(2, '\u516c\u958b'), (1, '\u4e0b\u66f8\u304d')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9'),
        ),
    ]
