# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=1024, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'confirmed'), (2, 'tentative'), (3, 'cancelled')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=1024, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'confirmed'), (2, 'tentative'), (3, 'cancelled')], default=1)),
            ],
        ),
    ]
