# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(default=datetime.datetime(2016, 2, 4, 4, 21, 32, 316491), verbose_name='\u7de8\u96c6\u65e5')),
                ('title', models.CharField(max_length=30, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('description', models.TextField(null=True, verbose_name='\u672c\u6587')),
                ('publish', models.BooleanField(default=True, verbose_name='\u516c\u958b\u3059\u308b')),
            ],
        ),
    ]
