# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'verbose_name': '\u7dca\u6025\u60c5\u5831', 'verbose_name_plural': '\u7dca\u6025\u60c5\u5831'},
        ),
        migrations.AlterModelManagers(
            name='emergency',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='mtime',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='publish',
        ),
        migrations.AddField(
            model_name='emergency',
            name='expires_on',
            field=models.DateTimeField(blank=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u4ee5\u964d\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u6709\u52b9\u671f\u9650'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='published_from',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 8, 9, 10, 9, 107956, tzinfo=utc), help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', verbose_name='\u516c\u958b\u958b\u59cb'),
            preserve_default=False,
        ),
    ]
