# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20160208_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='status',
            field=models.BooleanField(choices=[(False, '\u4e0b\u66f8\u304d'), (True, '\u516c\u958b\u3059\u308b')], default=datetime.datetime(2016, 2, 8, 9, 17, 43, 88605, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
