# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.BooleanField(choices=[(False, '\u4e0b\u66f8\u304d'), (True, '\u516c\u958b\u3059\u308b')], default=True),
        ),
    ]
