# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_auto_20160208_1843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emergency',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='emergency',
            name='published_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 21, 38, 31, 721491), help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', verbose_name='\u516c\u958b\u958b\u59cb'),
        ),
    ]
