# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0008_auto_20160217_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
