# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0009_delete_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyentrymodel',
            name='body',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='\u672c\u6587'),
        ),
    ]
