# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': '\u6d3b\u52d5\u9805\u76ee', 'verbose_name_plural': '\u6d3b\u52d5\u9805\u76ee'},
        ),
    ]
