# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20160223_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u672c\u6587'),
        ),
    ]
