# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20160228_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u672c\u6587'),
        ),
    ]
