# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20160228_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u984c\u540d'),
        ),
    ]
