# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='\u8cea\u554f')),
                ('answer', models.TextField(verbose_name='\u56de\u7b54')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '\u4e0b\u66f8\u304d'), (2, '\u516c\u958b')], default=2, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002', verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9')),
            ],
            options={
                'verbose_name': '\u3088\u304f\u3042\u308b\u8cea\u554f',
                'verbose_name_plural': '\u3088\u304f\u3042\u308b\u8cea\u554f',
            },
        ),
        migrations.AlterModelOptions(
            name='contactpostmodel',
            options={'verbose_name': '\u60c5\u5831\u63d0\u4f9b\u30fb\u304a\u554f\u3044\u5408\u308f\u305b\u9805\u76ee', 'verbose_name_plural': '\u60c5\u5831\u63d0\u4f9b\u30fb\u304a\u554f\u3044\u5408\u308f\u305b\u9805\u76ee'},
        ),
    ]
