# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactedmodel',
            old_name='contactedid',
            new_name='id',
        ),
    ]
