# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallReceiverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='\u4f5c\u6210\u65e5')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='\u7de8\u96c6\u65e5')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u540d\u524d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('active', models.BooleanField(default=True, verbose_name='\u53d7\u4fe1\u3059\u308b')),
            ],
            options={
                'verbose_name': '\u516c\u6c11\u9928\u7533\u8fbc\u307f\u53d7\u53d6\u4eba',
                'verbose_name_plural': '\u516c\u6c11\u9928\u7533\u8fbc\u307f\u53d7\u53d6\u4eba',
            },
        ),
        migrations.AlterModelOptions(
            name='contactreceivermodel',
            options={'verbose_name': '\u554f\u3044\u5408\u308f\u305b\u53d7\u53d6\u4eba', 'verbose_name_plural': '\u554f\u3044\u5408\u308f\u305b\u53d7\u53d6\u4eba'},
        ),
    ]
