# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160219_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQEntryModel',
            new_name='QAModel',
        ),
    ]
