# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160309_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
