# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20160309_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPostModel',
        ),
    ]
