# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20160219_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpostmodel',
            name='title',
        ),
    ]
