# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_contactpostmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpostmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9'),
        ),
    ]
