# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_contactpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedmodel',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u4f5c\u6210\u65e5'),
        ),
        migrations.AlterField(
            model_name='contactedmodel',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u7de8\u96c6\u65e5'),
        ),
        migrations.AlterField(
            model_name='contactedmodel',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe6\x9c\xaa\xe5\x87\xa6\xe7\x90\x86'), (2, b'\xe7\xa2\xba\xe8\xaa\x8d\xe6\xb8\x88'), (3, b'\xe5\x87\xa6\xe7\x90\x86\xe6\xb8\x88')], default=1, verbose_name='\u51e6\u7406\u72b6\u6cc1'),
        ),
        migrations.AlterField(
            model_name='contactreceivermodel',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u4f5c\u6210\u65e5'),
        ),
        migrations.AlterField(
            model_name='contactreceivermodel',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u7de8\u96c6\u65e5'),
        ),
    ]
