# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160220_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qamodel',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='\u56de\u7b54'),
        ),
    ]
