# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20160229_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u8981'),
        ),
    ]
