# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.CharField(default=datetime.datetime(2016, 2, 6, 23, 1, 42, 863349, tzinfo=utc), max_length=255, unique=True, verbose_name='Slag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='boards/', verbose_name='\u30b5\u30e0\u30cd\u30a4\u30eb'),
        ),
    ]
