# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160207_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='board',
            name='thumbnail',
        ),
    ]
