# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20160207_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='boards/', verbose_name='\u30b5\u30e0\u30cd\u30a4\u30eb'),
        ),
    ]
