# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:01
from __future__ import unicode_literals

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(upload_to='boards/', validators=[board.models.validate_file_pdf]),
        ),
    ]
