# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20160207_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='board',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='board',
            name='expires_on',
            field=models.DateTimeField(blank=True, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u4ee5\u964d\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', null=True, verbose_name='\u6709\u52b9\u671f\u9650'),
        ),
        migrations.AddField(
            model_name='board',
            name='published_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 23, 4, 57, 676721), help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', verbose_name='\u516c\u958b\u958b\u59cb'),
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(choices=[(False, '\u4e0b\u66f8\u304d'), (True, '\u516c\u958b\u3059\u308b')], default=True, help_text='\u4e0b\u66f8\u304d\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u30b5\u30a4\u30c8\u306e\u7ba1\u7406\u30e6\u30fc\u30b6\u30fc\u306e\u307f\u304c\u898b\u3089\u308c\u308b\u72b6\u614b\u306b\u306a\u308a\u307e\u3059\u3002'),
        ),
    ]
