# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20160208_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='published_from',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='\u516c\u958b\u3092\u9078\u629e\u3059\u308b\u3068\u3001\u3053\u3053\u3067\u8a2d\u5b9a\u3057\u305f\u65e5\u6642\u307e\u3067\u306f\u516c\u958b\u3055\u308c\u307e\u305b\u3093', verbose_name='\u516c\u958b\u958b\u59cb'),
        ),
    ]
